"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-06 16:48:21.199854
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('requirement_type', sa.String(), nullable=False),
    sa.Column('requirement_value', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(), nullable=False),
    sa.Column('reward_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('alliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('diplomacy', sa.String(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'world_id', name='uq_alliance_name_world')
    )
    op.create_index(op.f('ix_alliances_id'), 'alliances', ['id'], unique=False)
    op.create_table('item_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('bonus_type', sa.String(), nullable=False),
    sa.Column('bonus_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_templates_id'), 'item_templates', ['id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('reward', sa.JSON(), nullable=False),
    sa.Column('is_tutorial', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.create_index(op.f('ix_quests_quest_id'), 'quests', ['quest_id'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_index(op.f('ix_seasons_season_id'), 'seasons', ['season_id'], unique=True)
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price_rubies', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_shop_items_id'), 'shop_items', ['id'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_color', sa.String(), nullable=False),
    sa.Column('secondary_color', sa.String(), nullable=False),
    sa.Column('background_url', sa.String(), nullable=False),
    sa.Column('icon_pack_url', sa.String(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('protection_ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('rubies_balance', sa.Integer(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('freeze_reason', sa.String(), nullable=True),
    sa.Column('last_login_ip', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.Column('rename_tokens', sa.Integer(), nullable=False),
    sa.Column('tutorial_step', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('premium_theme_unlocked', sa.Boolean(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('attacker_points', sa.Integer(), nullable=False),
    sa.Column('defender_points', sa.Integer(), nullable=False),
    sa.Column('current_theme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wiki_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('BUILDINGS', 'TROOPS', 'COMBAT', 'ECONOMY', 'ESPIONAGE', 'EVENTS', 'BEGINNER', name='wikicategory'), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_wiki_articles_category'), 'wiki_articles', ['category'], unique=False)
    op.create_index(op.f('ix_wiki_articles_id'), 'wiki_articles', ['id'], unique=False)
    op.create_table('world_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_events_id'), 'world_events', ['id'], unique=False)
    op.create_index(op.f('ix_world_events_world_id'), 'world_events', ['world_id'], unique=False)
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('speed_modifier', sa.Float(), nullable=True),
    sa.Column('resource_modifier', sa.Float(), nullable=True),
    sa.Column('map_size', sa.Integer(), nullable=True),
    sa.Column('special_rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('winner_alliance_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_worlds_id'), 'worlds', ['id'], unique=False)
    # These three tables form an intentional domain cycle. Add their foreign
    # keys only after all tables exist so the migration works on PostgreSQL.
    with op.batch_alter_table('alliances') as batch_op:
        batch_op.create_foreign_key(
            'fk_alliances_leader_id_users', 'users', ['leader_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_alliances_world_id_worlds', 'worlds', ['world_id'], ['id']
        )
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_foreign_key(
            'fk_users_world_id_worlds', 'worlds', ['world_id'], ['id']
        )
    with op.batch_alter_table('worlds') as batch_op:
        batch_op.create_foreign_key(
            'fk_worlds_winner_id_users', 'users', ['winner_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_worlds_winner_alliance_id_alliances',
            'alliances',
            ['winner_alliance_id'],
            ['id'],
        )
    op.create_table('achievement_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_achievement_progress_id'), 'achievement_progress', ['id'], unique=False)
    op.create_table('admin_bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_bot_logs_id'), 'admin_bot_logs', ['id'], unique=False)
    op.create_table('alliance_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alliance_chat_messages_id'), 'alliance_chat_messages', ['id'], unique=False)
    op.create_table('alliance_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('invited_user_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alliance_id', 'invited_user_id', name='uq_alliance_invite_user')
    )
    op.create_index(op.f('ix_alliance_invitations_id'), 'alliance_invitations', ['id'], unique=False)
    op.create_table('alliance_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alliance_id', 'user_id', name='uq_alliance_member_user')
    )
    op.create_index(op.f('ix_alliance_members_id'), 'alliance_members', ['id'], unique=False)
    op.create_table('anti_cheat_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_of_violation', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_admin', sa.Boolean(), nullable=False),
    sa.Column('resolved_status', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anti_cheat_flags_id'), 'anti_cheat_flags', ['id'], unique=False)
    op.create_index(op.f('ix_anti_cheat_flags_user_id'), 'anti_cheat_flags', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('alliance_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('wood', sa.Float(), nullable=False),
    sa.Column('clay', sa.Float(), nullable=False),
    sa.Column('iron', sa.Float(), nullable=False),
    sa.Column('loyalty', sa.Float(), nullable=False),
    sa.Column('population_max', sa.Integer(), nullable=False),
    sa.Column('last_production', sa.DateTime(), nullable=False),
    sa.Column('researched_units', sa.JSON(), nullable=False),
    sa.Column('tile_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_world_id'), 'cities', ['world_id'], unique=False)
    op.create_table('diplomacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_a_id', sa.Integer(), nullable=False),
    sa.Column('alliance_b_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_a_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['alliance_b_id'], ['alliances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alliance_a_id', 'alliance_b_id', name='uq_diplomacy_pair')
    )
    op.create_index(op.f('ix_diplomacy_id'), 'diplomacy', ['id'], unique=False)
    op.create_table('forum_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_pinned', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_threads_id'), 'forum_threads', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('map_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_bookmarks_id'), 'map_bookmarks', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('premium_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rubies_balance', sa.Integer(), nullable=True),
    sa.Column('second_build_queue', sa.Boolean(), nullable=True),
    sa.Column('second_troop_queue', sa.Boolean(), nullable=True),
    sa.Column('rename_city_unlocked', sa.Boolean(), nullable=True),
    sa.Column('rename_player_unlocked', sa.Boolean(), nullable=True),
    sa.Column('extra_themes', sa.Boolean(), nullable=True),
    sa.Column('profile_banner', sa.Boolean(), nullable=True),
    sa.Column('instant_building_cancel', sa.Boolean(), nullable=True),
    sa.Column('increased_message_storage', sa.Boolean(), nullable=True),
    sa.Column('map_bookmarks', sa.Boolean(), nullable=True),
    sa.Column('selected_theme', sa.String(), nullable=True),
    sa.Column('selected_banner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_premium_status_id'), 'premium_status', ['id'], unique=False)
    op.create_table('quest_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_id', name='uq_user_quest')
    )
    op.create_index(op.f('ix_quest_progress_id'), 'quest_progress', ['id'], unique=False)
    op.create_index(op.f('ix_quest_progress_quest_id'), 'quest_progress', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_progress_user_id'), 'quest_progress', ['user_id'], unique=False)
    op.create_table('season_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rewards', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_results_id'), 'season_results', ['id'], unique=False)
    op.create_table('user_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_table('user_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'theme_id', name='uq_user_theme')
    )
    op.create_index(op.f('ix_user_themes_id'), 'user_themes', ['id'], unique=False)
    op.create_table('building_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('building_type', sa.String(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_queue_city_id'), 'building_queue', ['city_id'], unique=False)
    op.create_index(op.f('ix_building_queue_id'), 'building_queue', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_city_id'), 'buildings', ['city_id'], unique=False)
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_posts_id'), 'forum_posts', ['id'], unique=False)
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attack_points', sa.Integer(), nullable=False),
    sa.Column('defense_points', sa.Integer(), nullable=False),
    sa.Column('production_points', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=False)
    op.create_table('market_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('offer_type', sa.String(), nullable=False),
    sa.Column('offer_amount', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('request_amount', sa.Integer(), nullable=False),
    sa.Column('is_alliance_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_offers_id'), 'market_offers', ['id'], unique=False)
    op.create_table('oases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('bonus_percent', sa.Integer(), nullable=True),
    sa.Column('owner_city_id', sa.Integer(), nullable=True),
    sa.Column('troops', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oases_id'), 'oases', ['id'], unique=False)
    op.create_table('player_world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('starting_city_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['starting_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'world_id', name='uq_player_world_user_world')
    )
    op.create_index(op.f('ix_player_world_id'), 'player_world', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('attacker_city_id', sa.Integer(), nullable=True),
    sa.Column('defender_city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['defender_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('tech_name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_city_id'), 'research', ['city_id'], unique=False)
    op.create_index(op.f('ix_research_id'), 'research', ['id'], unique=False)
    op.create_table('spy_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('attacker_city_id', sa.Integer(), nullable=True),
    sa.Column('defender_city_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('reported_as_unknown', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['defender_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spy_reports_id'), 'spy_reports', ['id'], unique=False)
    op.create_table('troop_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('troop_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_troop_queue_city_id'), 'troop_queue', ['city_id'], unique=False)
    op.create_index(op.f('ix_troop_queue_id'), 'troop_queue', ['id'], unique=False)
    op.create_table('troops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_troops_city_id'), 'troops', ['city_id'], unique=False)
    op.create_index(op.f('ix_troops_id'), 'troops', ['id'], unique=False)
    op.create_table('adventures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adventures_id'), 'adventures', ['id'], unique=False)
    op.create_table('hero_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['item_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_items_id'), 'hero_items', ['id'], unique=False)
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_city_id', sa.Integer(), nullable=True),
    sa.Column('target_city_id', sa.Integer(), nullable=True),
    sa.Column('target_oasis_id', sa.Integer(), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('troops', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('spy_count', sa.Integer(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('speed_used', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('target_building', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['target_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['target_oasis_id'], ['oases.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worlds') as batch_op:
        batch_op.drop_constraint(
            'fk_worlds_winner_alliance_id_alliances', type_='foreignkey'
        )
        batch_op.drop_constraint('fk_worlds_winner_id_users', type_='foreignkey')
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_world_id_worlds', type_='foreignkey')
    with op.batch_alter_table('alliances') as batch_op:
        batch_op.drop_constraint('fk_alliances_world_id_worlds', type_='foreignkey')
        batch_op.drop_constraint('fk_alliances_leader_id_users', type_='foreignkey')
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_hero_items_id'), table_name='hero_items')
    op.drop_table('hero_items')
    op.drop_index(op.f('ix_adventures_id'), table_name='adventures')
    op.drop_table('adventures')
    op.drop_index(op.f('ix_troops_id'), table_name='troops')
    op.drop_index(op.f('ix_troops_city_id'), table_name='troops')
    op.drop_table('troops')
    op.drop_index(op.f('ix_troop_queue_id'), table_name='troop_queue')
    op.drop_index(op.f('ix_troop_queue_city_id'), table_name='troop_queue')
    op.drop_table('troop_queue')
    op.drop_index(op.f('ix_spy_reports_id'), table_name='spy_reports')
    op.drop_table('spy_reports')
    op.drop_index(op.f('ix_research_id'), table_name='research')
    op.drop_index(op.f('ix_research_city_id'), table_name='research')
    op.drop_table('research')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_player_world_id'), table_name='player_world')
    op.drop_table('player_world')
    op.drop_index(op.f('ix_oases_id'), table_name='oases')
    op.drop_table('oases')
    op.drop_index(op.f('ix_market_offers_id'), table_name='market_offers')
    op.drop_table('market_offers')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_index(op.f('ix_forum_posts_id'), table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_city_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_building_queue_id'), table_name='building_queue')
    op.drop_index(op.f('ix_building_queue_city_id'), table_name='building_queue')
    op.drop_table('building_queue')
    op.drop_index(op.f('ix_user_themes_id'), table_name='user_themes')
    op.drop_table('user_themes')
    op.drop_table('user_items')
    op.drop_index(op.f('ix_season_results_id'), table_name='season_results')
    op.drop_table('season_results')
    op.drop_index(op.f('ix_quest_progress_user_id'), table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_quest_id'), table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    op.drop_index(op.f('ix_premium_status_id'), table_name='premium_status')
    op.drop_table('premium_status')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_map_bookmarks_id'), table_name='map_bookmarks')
    op.drop_table('map_bookmarks')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_forum_threads_id'), table_name='forum_threads')
    op.drop_table('forum_threads')
    op.drop_index(op.f('ix_diplomacy_id'), table_name='diplomacy')
    op.drop_table('diplomacy')
    op.drop_index(op.f('ix_cities_world_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_anti_cheat_flags_user_id'), table_name='anti_cheat_flags')
    op.drop_index(op.f('ix_anti_cheat_flags_id'), table_name='anti_cheat_flags')
    op.drop_table('anti_cheat_flags')
    op.drop_index(op.f('ix_alliance_members_id'), table_name='alliance_members')
    op.drop_table('alliance_members')
    op.drop_index(op.f('ix_alliance_invitations_id'), table_name='alliance_invitations')
    op.drop_table('alliance_invitations')
    op.drop_index(op.f('ix_alliance_chat_messages_id'), table_name='alliance_chat_messages')
    op.drop_table('alliance_chat_messages')
    op.drop_index(op.f('ix_admin_bot_logs_id'), table_name='admin_bot_logs')
    op.drop_table('admin_bot_logs')
    op.drop_index(op.f('ix_achievement_progress_id'), table_name='achievement_progress')
    op.drop_table('achievement_progress')
    op.drop_index(op.f('ix_worlds_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_world_events_world_id'), table_name='world_events')
    op.drop_index(op.f('ix_world_events_id'), table_name='world_events')
    op.drop_table('world_events')
    op.drop_index(op.f('ix_wiki_articles_id'), table_name='wiki_articles')
    op.drop_index(op.f('ix_wiki_articles_category'), table_name='wiki_articles')
    op.drop_table('wiki_articles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_shop_items_id'), table_name='shop_items')
    op.drop_table('shop_items')
    op.drop_index(op.f('ix_seasons_season_id'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_quests_quest_id'), table_name='quests')
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_item_templates_id'), table_name='item_templates')
    op.drop_table('item_templates')
    op.drop_index(op.f('ix_alliances_id'), table_name='alliances')
    op.drop_table('alliances')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
